version: '2.1'

services:
    shell:
        # build:
        #     context: .
        #     dockerfile: sParts.Dockerfile
        image: phyohtut/sparts-test:latest
        # image: sameerfarooq/sparts-test:latest
        environment:
            - NAME_=phyo
            - EMAIL_=phyo.htut@windriver.com
            - ROLE_=admin
        container_name: phyo
        expose:
            - '818' # sParts api
            - '850' # category api
            - '851' # organization api
            - '852' # part api
            # - '853' # artifact api
            # - '80'
        ports:
            - '8080:818'
            - '8800:850'
            - '8880:851'
            - '8888:852'
            # - '0808:853'
            # - '80:80'
        tty: true
        volumes:
            - ./phyo:/project/src
            - ./api/sparts-api.py:/project/sparts-api.py
        # RUNNING FROM phyohtut/sparts-test:part
        entrypoint: "bash -c \"\
            cd /project/src/tp_artifact_1.0 && \
            python3 setup.py install && \
            cd /project/src/tp_part_1.0 && \
            python3 setup.py install && \
            cd /project/src/tp_category_1.0 && \
            python3 setup.py install && \
            cd /project/src/tp_organization_1.0 && \
            python3 setup.py install && \
            cd /project/ledger-startup-scripts && \
            ./sparts_ledger.sh && \
            cd /project/src && \
            curl http://127.0.0.1:818/ledger/api/v1/keys > keys.txt && echo '' >> keys.txt && \
            echo '====================READY TO EXECUTE THE BASH====================' && \
            echo 'docker exec -it phyo bash' && \
            python3 lazy_user.py && \
            rm -rf keys.txt && \
            echo '====================READY TO EXECUTE THE BASH====================' && \
            tail -f /dev/null \
            \""
        
        # RUNNING FROM sameerfarooq/sparts-test:latest
        # entrypoint: "bash -c \"\
        #     apt-get update && \
        #     apt-get install -y curl && \
        #     rm -rf /var/lib/apt/lists/* && \
        #     cd /project/src/tp_artifact_1.0 && \
        #     python3 setup.py install && \
        #     cd /project/src/tp_part_1.0 && \
        #     python3 setup.py install && \
        #     cd /project/src/tp_category_1.0 && \
        #     python3 setup.py install && \
        #     cd /project/src/tp_organization_1.0 && \
        #     python3 setup.py install && \
        #     cd /project/ledger-startup-scripts && \
        #     ./sparts_ledger.sh && \
        #     cd /project/src && \
        #     curl http://localhost:818/ledger/api/v1/keys > keys.txt && echo '' >> keys.txt && \
        #     echo '====================READY TO EXECUTE THE BASH====================' && \
        #     echo 'docker exec -it phyo bash' && \
        #     python3 lazy_user.py && \
        #     rm -rf keys.txt && \
        #     echo '====================READY TO EXECUTE THE BASH====================' && \
        #     tail -f /dev/null \
        #     \""
